language: go
go:
  - 1.13.x
os:
  - linux
dist: trusty
install: true

env:
  - CC_TEST_REPORTER_ID=9cc8d6f658996ba4d94c148c02e551e3be69977dc930054b442cfcccc775ec3d
  - SONAR_TOKEN=09a24bce4ec02d6fada6b9726cfd9431bb3839f7
  - GO111MODULE=on

script:
  - go mod download
  - go test -short -coverprofile=cov.out `go list ./...`
  - sonar-scanner

addons:
  sonarcloud:
    organization: "apssouza22-github"
    token:
      secure: "09a24bce4ec02d6fada6b9726cfd9431bb3839f7" # encrypted value of your token
