language: go
go:
  - 1.13.x
os:
  - linux
dist: trusty
install: true

env:
  - CC_TEST_REPORTER_ID=9cc8d6f658996ba4d94c148c02e551e3be69977dc930054b442cfcccc775ec3d
  - SONAR_TOKEN=feth8AVhWpiQJlNxaEKK80RfEsMD46yRDsjplC/3IzCvNrPpVryYG+ygceHyPvrCy5OEh0mDdpdEKIoNS5LIUGv3Kw6Rt+p1rjAKAyQIKzvSOQqyoXi+w+CmC5rCgNeB6yJv/ogXFDZjHv42MymZWacKCFXErrxe6V/XckqkDMVyDcp9Ddby+W9SxlWjgPNTcnC36RcyYZ/Aj+N97fBIb5pBeWYbkYI2+I+AuZ4KvpohMfsdHKQXL873Dg/DR8aSHgk/7Ozxsg+3s3t6wb0E2uwlhnAI+W2Qzhf7TM+yqJa70gjftJaoVxvzoFkF9oVlgGk2IAfWzlXZBNeVtLQddHLUP1Gixdbxx433G3oM0s5Nm9cIj1/BqwefWJhn59zUJpT8c3phFk4MOFalrkIbq0g9IgjN4nk2ReG4Sk8JqYVmLvs4JUlKElJHzP30Y9coVnQbWl8ic6cjoXUXRmybHpUyE8iNhtbw7Yy3rZ+74rlkxLVxRtpap6YLijxovdplhBMGPoC0hSbbz+qvRjJcGwF2gUZlyiiQWqrOrb9BQsTj7dN/sAbnLqToEpzvQyNbnH2lbv/mrfQ5kqAcaArcpmfXEPg7p8omDtoI5isFoTYxQDAU2En1q7W0MSyD7r1EUXGHzZV2ZeCewLRZ+KevCDSySpI4LD49KhH0/UdGGcQ=
  - GO111MODULE=on

script:
  - go mod download
  - go test -short -coverprofile=cov.out `go list ./...`
  - sonar-scanner

addons:
  sonarcloud:
    organization: "apssouza22-github"
    token:
      secure: "feth8AVhWpiQJlNxaEKK80RfEsMD46yRDsjplC/3IzCvNrPpVryYG+ygceHyPvrCy5OEh0mDdpdEKIoNS5LIUGv3Kw6Rt+p1rjAKAyQIKzvSOQqyoXi+w+CmC5rCgNeB6yJv/ogXFDZjHv42MymZWacKCFXErrxe6V/XckqkDMVyDcp9Ddby+W9SxlWjgPNTcnC36RcyYZ/Aj+N97fBIb5pBeWYbkYI2+I+AuZ4KvpohMfsdHKQXL873Dg/DR8aSHgk/7Ozxsg+3s3t6wb0E2uwlhnAI+W2Qzhf7TM+yqJa70gjftJaoVxvzoFkF9oVlgGk2IAfWzlXZBNeVtLQddHLUP1Gixdbxx433G3oM0s5Nm9cIj1/BqwefWJhn59zUJpT8c3phFk4MOFalrkIbq0g9IgjN4nk2ReG4Sk8JqYVmLvs4JUlKElJHzP30Y9coVnQbWl8ic6cjoXUXRmybHpUyE8iNhtbw7Yy3rZ+74rlkxLVxRtpap6YLijxovdplhBMGPoC0hSbbz+qvRjJcGwF2gUZlyiiQWqrOrb9BQsTj7dN/sAbnLqToEpzvQyNbnH2lbv/mrfQ5kqAcaArcpmfXEPg7p8omDtoI5isFoTYxQDAU2En1q7W0MSyD7r1EUXGHzZV2ZeCewLRZ+KevCDSySpI4LD49KhH0/UdGGcQ=" # encrypted value of your token
